BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "android_metadata" (
	"locale"	TEXT
);
CREATE TABLE IF NOT EXISTS "THANHVIEN" (
	"MATHANHVIEN"	INTEGER,
	"HOTENTHANHVIEN"	TEXT NOT NULL,
	"NAMSINHTHANHVIEN"	INTEGER NOT NULL,
	"TAIKHOANTHANHVIEN"	TEXT NOT NULL,
	"MATKHAUTHANHVIEN"	TEXT NOT NULL,
	PRIMARY KEY("MATHANHVIEN")
);
CREATE TABLE IF NOT EXISTS "THUTHU" (
	"MATHUTHU"	INTEGER,
	"HOTENTHUTHU"	TEXT NOT NULL,
	"TAIKHOANTHUTHU"	TEXT NOT NULL,
	"MATKHAUTHUTHU"	TEXT NOT NULL,
	"IMAGETHUTHU"	BLOB,
	PRIMARY KEY("MATHUTHU" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "LOAISACH" (
	"MALOAISACH"	INTEGER,
	"TENLOAISACH"	TEXT NOT NULL,
	PRIMARY KEY("MALOAISACH" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "SACH" (
	"MASACH"	INTEGER,
	"TENSACH"	TEXT NOT NULL,
	"GIATHUE"	MONEY NOT NULL,
	"KHUYENMAI"	MONEY,
	"LOAISACH"	INTEGER,
	PRIMARY KEY("MASACH" AUTOINCREMENT),
	FOREIGN KEY("LOAISACH") REFERENCES "LOAISACH"("LOAISACH")
);
CREATE TABLE IF NOT EXISTS "PHIEUMUONSACH" (
	"MAPHIEUMUON"	INTEGER,
	"MATHUTHU"	INTEGER,
	"MATHANHVIEN"	INTEGER,
	"MASACH"	INTEGER,
	"TIENTHUE"	MONEY NOT NULL,
	"NGAYMUON"	DATE NOT NULL,
	"NGAYTRA"	DATE NOT NULL,
	"TRASACH"	INTEGER NOT NULL,
	PRIMARY KEY("MAPHIEUMUON" AUTOINCREMENT),
	FOREIGN KEY("MATHUTHU") REFERENCES "THUTHU"("MATHUTHU"),
	FOREIGN KEY("MATHANHVIEN") REFERENCES "THANHVIEN"("MATHANHVIEN"),
	FOREIGN KEY("MASACH") REFERENCES "SACH"("MASACH")
);
CREATE TABLE IF NOT EXISTS "NHAXUATBAN" (
	"MANXB"	INTEGER,
	"TEN"	TEXT NOT NULL,
	"DIACHI"	TEXT NOT NULL,
	"SDT"	TEXT NOT NULL,
	PRIMARY KEY("MANXB" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "PHIEUNHAPSACH" (
	"MAPHIEUNHAP"	INTEGER,
	"TENTG"	TEXT NOT NULL,
	"MATT"	TEXT NOT NULL,
	"MASACH"	TEXT NOT NULL,
	"NGAYNHAP"	TEXT NOT NULL,
	"SOLUONG"	INTEGER NOT NULL,
	"MANXB"	TEXT NOT NULL,
	PRIMARY KEY("MAPHIEUNHAP" AUTOINCREMENT)
);
INSERT INTO "android_metadata" ("locale") VALUES ('en_US');
INSERT INTO "THANHVIEN" ("MATHANHVIEN","HOTENTHANHVIEN","NAMSINHTHANHVIEN","TAIKHOANTHANHVIEN","MATKHAUTHANHVIEN") VALUES (111,'VÂN ANH',2002,'VANANH','VANANH');
INSERT INTO "THANHVIEN" ("MATHANHVIEN","HOTENTHANHVIEN","NAMSINHTHANHVIEN","TAIKHOANTHANHVIEN","MATKHAUTHANHVIEN") VALUES (222,'HOÀNG NHẬT',2003,'HOANGNHAT','HOANGNHAT');
INSERT INTO "THANHVIEN" ("MATHANHVIEN","HOTENTHANHVIEN","NAMSINHTHANHVIEN","TAIKHOANTHANHVIEN","MATKHAUTHANHVIEN") VALUES (333,'THỚI VIỆT TRÀ',2002,'VIETTRA','VIETTRA');
INSERT INTO "THANHVIEN" ("MATHANHVIEN","HOTENTHANHVIEN","NAMSINHTHANHVIEN","TAIKHOANTHANHVIEN","MATKHAUTHANHVIEN") VALUES (444,'LỆ THỦY',2003,'LETHUY','LETHUY');
INSERT INTO "THANHVIEN" ("MATHANHVIEN","HOTENTHANHVIEN","NAMSINHTHANHVIEN","TAIKHOANTHANHVIEN","MATKHAUTHANHVIEN") VALUES (555,'MINH MINH',2000,'MINHMINH','MINHMINH');
INSERT INTO "THANHVIEN" ("MATHANHVIEN","HOTENTHANHVIEN","NAMSINHTHANHVIEN","TAIKHOANTHANHVIEN","MATKHAUTHANHVIEN") VALUES (666,'THÀNH VŨ',2001,'THANHVU','THANHVU');
INSERT INTO "THUTHU" ("MATHUTHU","HOTENTHUTHU","TAIKHOANTHUTHU","MATKHAUTHUTHU","IMAGETHUTHU") VALUES (1,'LÂM HỒ THIÊN TỐNG','thientong','thientong',NULL);
INSERT INTO "THUTHU" ("MATHUTHU","HOTENTHUTHU","TAIKHOANTHUTHU","MATKHAUTHUTHU","IMAGETHUTHU") VALUES (2,'NGUYỄN THỊ KIM KIỀU','kimkieu','kimkieu',NULL);
INSERT INTO "LOAISACH" ("MALOAISACH","TENLOAISACH") VALUES (1,'SELF-HELP BOOK');
INSERT INTO "LOAISACH" ("MALOAISACH","TENLOAISACH") VALUES (2,'ENGLISH');
INSERT INTO "LOAISACH" ("MALOAISACH","TENLOAISACH") VALUES (3,'COMIC');
INSERT INTO "LOAISACH" ("MALOAISACH","TENLOAISACH") VALUES (4,'NOVEL');
INSERT INTO "SACH" ("MASACH","TENSACH","GIATHUE","KHUYENMAI","LOAISACH") VALUES (11,'ONENESS WITH ALL LIFE',12,24,1);
INSERT INTO "SACH" ("MASACH","TENSACH","GIATHUE","KHUYENMAI","LOAISACH") VALUES (33,'AMERICAN BORN CHINESE',18,35,3);
INSERT INTO "SACH" ("MASACH","TENSACH","GIATHUE","KHUYENMAI","LOAISACH") VALUES (44,'THE ANXIETY TOOLKIT',19,28,1);
INSERT INTO "SACH" ("MASACH","TENSACH","GIATHUE","KHUYENMAI","LOAISACH") VALUES (55,'A DEATH IN THE FAMILY',12,43,3);
INSERT INTO "SACH" ("MASACH","TENSACH","GIATHUE","KHUYENMAI","LOAISACH") VALUES (66,'A STEP FROM HEAVEN',36,54,4);
INSERT INTO "SACH" ("MASACH","TENSACH","GIATHUE","KHUYENMAI","LOAISACH") VALUES (222,'TOEFL IBT PREP',14,26,2);
INSERT INTO "PHIEUMUONSACH" ("MAPHIEUMUON","MATHUTHU","MATHANHVIEN","MASACH","TIENTHUE","NGAYMUON","NGAYTRA","TRASACH") VALUES (1,1,555,55,6.84000015258789,'2022-12-04','2022-12-11',1);
COMMIT;
